// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_phonebook/test/services/contact_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_phonebook/models/contact.dart' as _i2;
import 'package:flutter_phonebook/services/contact_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContact_0 extends _i1.SmartFake implements _i2.Contact {
  _FakeContact_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContactApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactApi extends _i1.Mock implements _i3.ContactApi {
  MockContactApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Contact>> getAllContacts() => (super.noSuchMethod(
        Invocation.method(
          #getAllContacts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
      ) as _i4.Future<List<_i2.Contact>>);
  @override
  _i4.Future<_i2.Contact> addContact(_i2.Contact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [contact],
        ),
        returnValue: _i4.Future<_i2.Contact>.value(_FakeContact_0(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
      ) as _i4.Future<_i2.Contact>);
  @override
  _i4.Future<bool> editContact(_i2.Contact? contact) => (super.noSuchMethod(
        Invocation.method(
          #editContact,
          [contact],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> deleteContact(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteContact,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
